
const OpensData = [
    {
      id: 1,
      image:
      "https://img.kapital.kz/Del6E1oO__g/bG9jYWw6Ly8vNi9lLzMvYy9mLzY2Y2FlZjllYzE0OGE3YzVkODkyMmI0Y2Y2NC5qcGc",
      name: "KBTU OPEN",
      uni: "Kazakh-British Technical University",
       q0:"KBTU OPEN registration dates",
       q1:"What is KBTU OPEN ?",
       q2:"Where is the event taking place?",
       q3:"Who are eligible to participate?",
       q4:"How many people should be in a team?",
       q5:"Who have prepared the problems?",
       q6:"Where can i find more information about KBTU open?",
       a0:"Mostly in spring, but you can monitor it here: https://t.me/kbtuopen",
       a1:"KBTU OPEN is an annual multi-tiered competitive programming competition among the  universities of the Kazakhstan",
       a2:"The event is taking place at Kazakh-British Technical University,located at Tole-bi street 59, Almaty. The entrance is from Abylaykhan street side.",
       a3:"The entire competition will be held both onsite and online, and everyone is welcome to participate!",
       a4:"Teams should be formed out of a maximum of three people",
       a5:"All the problems have been prepared by KBTU students and alumni",
       a6:"Here!: https://kbtuopen.com/ and Here!: https://t.me/kbtuopen",
    },
    {
        id: 2,
        image:
        "https://yt3.googleusercontent.com/2ha_gBZFSb6WqDbX_hDm8PqGpzKpEC1vVcPqvm9AUxM5Yp-I2WHWsuOyTyhzO4njwx4rCMRFGw=s900-c-k-c0x00ffffff-no-rj",
        name: "NU OPEN",
        uni: "Nazarbayev University",
        description:"Every year Competition in NU",
        q0:"NU OPEN registration dates",
        q1:"What is NU OPEN ?",
        q2:"Where is the event taking place?",
        q3:"Who are eligible to participate?",
        q4:"How many people should be in a team?",
        q5:"Who have prepared the problems?",
        q6:"Where can i find more information about NU open?",
        a0:"Autumn-Winter period, but you can monitor it here: https://t.me/nuopen",
        a1:"NU OPEN is a Republican Competitive Programming Contest for all willing to challenge and improve their programming skills",
        a2:"The event is taking place at Nazarbayev university,located at 53 Kabanbay Batyr Ave, Astana city",
        a3:"The entire competition will be held both onsite and online, and everyone is welcome to participate! *only bachelor and high school students are eligible for prizes",
        a4:"Teams should be formed out of a maximum of three people",
        a5:"All the problems have been prepared by NU students and alumni",
        a6:"Here!: https://open.nuacm.kz/ and Here!: https://t.me/nuopen",
    },
    {
        id: 3,
        image:
        "https://iitu.edu.kz/media/images/CP3.original.format-jpeg.jpg",
        name: "IITU OPEN",
        uni: "International IT University",
        description:"Every year Competition in IITU",
        q0:"IITU OPEN registration dates",
        q1:"What is IITU OPEN ?",
        q2:"Where is the event taking place?",
        q3:"Who are eligible to participate?",
        q4:"How many people should be in a team?",
        q5:"Who have prepared the problems?",
        q6:"Where can i find more information about IITU open?",
        a0:"you can monitor it here: https://iitu.edu.kz/ru/news/iitu-open-2023/",
        a1:"IITU OPEN is a Republican Competitive Programming Contest for all willing to challenge and improve their programming skills",
        a2:"The event is taking place at International IT University,located at 34/1 Manas Street,Bostandyk district, Almaty city",
        a3:"The entire competition will be held both onsite and online",
        a4:"Teams should be formed out of a maximum of three people",
        a5:"All the problems have been prepared by IITU students",
        a6:"Here!: https://iitu.edu.kz/ru/news/iitu-open-2023/",
    },
    {
        id: 4,
        image:
        "https://astanait.edu.kz/wp-content/uploads/2020/11/DSC01501-scaled.jpg",
        name: "AITU OPEN",
        uni: "AITU University",
        description:"Every year Competition in AITU",
        q0:"AITU OPEN registration dates",
        q1:"What is AITU OPEN ?",
        q2:"Where is the event taking place?",
        q3:"Who are eligible to participate?",
        q4:"How many people should be in a team?",
        q5:"Who have prepared the problems?",
        q6:"Where can i find more information about AITU open?",
        a0:"Spring period, but you can monitor it here: https://t.me/aituopen",
        a1:"AITU OPEN is a contest algorithmic programming, which are distinguished by a high level of mathematics, require knowledge of algorithms and data structures for their implementation",
        a2:"The event is taking place at AITU,located at Mangilik El avenue, 55/11,Business center EXPO, block C1,Astana",
        a3:"The entire competition will be held both onsite and online",
        a4:"Teams should be formed out of a maximum of three people",
        a5:"All the problems have been prepared by AITU students and alumni",
        a6:"Here!: https://t.me/aituopen",
    },
    {
        id: 5,
        image:
        "https://samatshow.kz/wp-content/uploads/2019/08/university-demriel.jpg",
        name: "SDU OPEN ",
        uni: "Suleyman Demirel University",
        description:"-",
        q0:"SDU OPEN registration dates",
        q1:"What is SDU OPEN??",
        q2:"Where is the event taking place?",
        q3:"Who are eligible to participate?",
        q4:"How many people should be in a team?",
        q5:"Who have prepared the problems?",
        q6:"Where can i find more information about SDU OPEN?",
        a0:"The registration dates for SDU OPEN may vary each year, you can monitor it here: https://open.sdu.edu.kz/",
        a1:"SDU OPEN is an annual multi-tiered competitive programming competition among the  universities of the Kazakhstan",
        a2:"The event is taking place at SDU,located at Kaskelen, Almaty Region",
        a3:"Anyone all over the Kazakhstan",
        a4:"Teams should be formed out of a maximum of 3 people.",
        a5:"The problems for the SDU OPEN are designed by a team of experienced problem setters and coordinators",
        a6:"Here!: https://open.sdu.edu.kz/ ",
    },
    {
        id: 6,
        image:
        "https://icpc.global/community/world-finals-champions/2018.jpg",
        name: "International Collegiate Programming Contest",
        uni: "",
        description:"-",
        q0:"ICPC OPEN registration dates",
        q1:"What is ICPC?",
        q2:"Where is the event taking place?",
        q3:"Who are eligible to participate?",
        q4:"How many people should be in a team?",
        q5:"Who have prepared the problems?",
        q6:"Where can i find more information about ICPC ?",
        a0:"The registration dates for ICPC vary each year. You can find registration details on the official ICPC website: https://icpc.global/",
        a1:"The International Collegiate Programming Contest (ICPC) is an annual multi-tiered competitive programming competition among universities from around the world",
        a2:"ICPC events are held in different locations each year. ",
        a3:"The ICPC is open to university students from all around the world.",
        a4:"Teams should be formed out of a maximum of three people",
        a5:"The problems for the ICPC are crafted by a team of experienced problem setters",
        a6:"For more detailed information about ICPC, including the competition schedule, rules, and resources, you can visit the official ICPC website: https://icpc.global/",
    },
  ];
  export default OpensData;